---
swagger: "2.0"
info:
  description: "Enables CRUD on Route object and Routes messages to approproate RabbitMQ\
    \ queues"
  version: "1.0.0"
  title: "Routing Service"
  contact:
    name: "EIP Team"
    email: "eipteam@cdc.gov"
  license:
    name: "eip"
    url: "http://unlicense.org"
host: "localhost:10001"
basePath: "/routing-services"
tags:
- name: "info-service-controller"
  description: "Info Service Controller"
- name: "routing-controller"
  description: "Routing Controller"
paths:
  /v1/info/about:
    get:
      tags:
      - "info-service-controller"
      summary: "about"
      operationId: "aboutUsingGET"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/About"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
  /v1/info/ping:
    get:
      tags:
      - "info-service-controller"
      summary: "ping"
      operationId: "pingUsingGET"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      responses:
        200:
          description: "OK"
          schema:
            type: "string"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
  /v1/info/version:
    get:
      tags:
      - "info-service-controller"
      summary: "getVersion"
      operationId: "getVersionUsingGET"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      responses:
        200:
          description: "OK"
          schema:
            type: "string"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
  /v1/route:
    post:
      tags:
      - "routing-controller"
      summary: "Create a Route resources"
      description: "Create a Route resources"
      operationId: "createUsingPOST"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      - "*/*"
      parameters:
      - in: "body"
        name: "route"
        description: "route"
        required: true
        schema:
          $ref: "#/definitions/Route"
      responses:
        200:
          description: "Route successfully created"
          schema:
            $ref: "#/definitions/_SWRoute"
        201:
          description: "Created"
        400:
          description: "Any error that is caused by the user - bad data sent, business\
            \ rules violated, etc"
        401:
          description: "Unauthorized"
        500:
          description: "Any Server side error can be reported via a 500. those errors\
            \ are not recoverable by they user - something is wrong with the system"
        403:
          description: "Caller is not authorized to execute this method"
        404:
          description: "Not Found"
        409:
          description: "Conflict"
    put:
      tags:
      - "routing-controller"
      summary: "Update a Route resources"
      description: "Update a Route resources"
      operationId: "updateUsingPUT"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      - "*/*"
      parameters:
      - in: "body"
        name: "route"
        description: "route"
        required: true
        schema:
          $ref: "#/definitions/Route"
      responses:
        200:
          description: "Route successfully updated"
          schema:
            $ref: "#/definitions/_SWRoute"
        201:
          description: "Created"
        400:
          description: "Any error that is caused by the user - bad data sent, business\
            \ rules violated, etc"
        401:
          description: "Unauthorized"
        500:
          description: "Any Server side error can be reported via a 500. those errors\
            \ are not recoverable by they user - something is wrong with the system"
        403:
          description: "Caller is not authorized to execute this method"
        404:
          description: "Not Found"
        409:
          description: "Conflict"
  /v1/route/{routeId}:
    get:
      tags:
      - "routing-controller"
      summary: "Get Route resource for a soecific routeId"
      description: "Get Route resource for a soecific routeId"
      operationId: "getRouteUsingGET"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      - "*/*"
      parameters:
      - name: "routeId"
        in: "path"
        description: "routeId"
        required: true
        type: "string"
      responses:
        200:
          description: "Registration successfully created"
          schema:
            $ref: "#/definitions/_SWRoute"
        400:
          description: "Any error that is caused by the user - bad data sent, business\
            \ rules violated, etc"
        401:
          description: "Unauthorized"
        500:
          description: "Any Server side error can be reported via a 500. those errors\
            \ are not recoverable by they user - something is wrong with the system"
        403:
          description: "Caller is not authorized to execute this method"
        404:
          description: "Not Found"
        409:
          description: "Conflict"
  /v1/route/{routeId},{userSuppliedVersion}:
    put:
      tags:
      - "routing-controller"
      summary: "Delete a Route resource"
      description: "Delete a Route resource"
      operationId: "deleteUsingPUT"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      - "*/*"
      parameters:
      - name: "routeId"
        in: "path"
        description: "routeId"
        required: true
        type: "string"
      - name: "userSuppliedVersion"
        in: "path"
        description: "userSuppliedVersion"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Route successfully deleted"
          schema:
            $ref: "#/definitions/_SWRoute"
        201:
          description: "Created"
        400:
          description: "Any error that is caused by the user - bad data sent, business\
            \ rules violated, etc"
        401:
          description: "Unauthorized"
        500:
          description: "Any Server side error can be reported via a 500. those errors\
            \ are not recoverable by they user - something is wrong with the system"
        403:
          description: "Caller is not authorized to execute this method"
        404:
          description: "Not Found"
        409:
          description: "Conflict"
  /v1/routeMessage:
    post:
      tags:
      - "routing-controller"
      summary: "Routes Message with guid to for a specific rabitmq queue for condition\
        \ code"
      description: "Routes Message with guid to for a specific rabitmq queue for condition\
        \ code"
      operationId: "routeMessageUsingPOST"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      parameters:
      - name: "condition"
        in: "query"
        description: "condition"
        required: true
        type: "string"
      - name: "mguid"
        in: "query"
        description: "mguid"
        required: true
        type: "string"
      responses:
        200:
          description: "Routing successfully done"
          schema:
            type: "string"
        201:
          description: "Created"
        400:
          description: "Any error that is caused by the user - bad data sent, business\
            \ rules violated, etc"
        401:
          description: "Unauthorized"
        500:
          description: "Any Server side error can be reported via a 500. those errors\
            \ are not recoverable by they user - something is wrong with the system"
        403:
          description: "Caller is not authorized to execute this method"
        404:
          description: "Not Found"
        207:
          description: "Routing partially done with multi status"
          schema:
            type: "string"
  /v1/routes:
    get:
      tags:
      - "routing-controller"
      summary: "Get all Route resources"
      description: "Get all Route resources"
      operationId: "getRoutesUsingGET"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      - "*/*"
      responses:
        200:
          description: "Registration successfully created"
          schema:
            $ref: "#/definitions/_SWRoute"
        400:
          description: "Any error that is caused by the user - bad data sent, business\
            \ rules violated, etc"
        401:
          description: "Unauthorized"
        500:
          description: "Any Server side error can be reported via a 500. those errors\
            \ are not recoverable by they user - something is wrong with the system"
        403:
          description: "Caller is not authorized to execute this method"
        404:
          description: "Not Found"
        409:
          description: "Conflict"
definitions:
  ResponseEntity:
    type: "object"
    properties:
      body:
        type: "object"
      statusCode:
        type: "string"
        enum:
        - "100"
        - "101"
        - "102"
        - "103"
        - "200"
        - "201"
        - "202"
        - "203"
        - "204"
        - "205"
        - "206"
        - "207"
        - "208"
        - "226"
        - "300"
        - "301"
        - "302"
        - "303"
        - "304"
        - "305"
        - "307"
        - "308"
        - "400"
        - "401"
        - "402"
        - "403"
        - "404"
        - "405"
        - "406"
        - "407"
        - "408"
        - "409"
        - "410"
        - "411"
        - "412"
        - "413"
        - "414"
        - "415"
        - "416"
        - "417"
        - "418"
        - "419"
        - "420"
        - "421"
        - "422"
        - "423"
        - "424"
        - "426"
        - "428"
        - "429"
        - "431"
        - "451"
        - "500"
        - "501"
        - "502"
        - "503"
        - "504"
        - "505"
        - "506"
        - "507"
        - "508"
        - "509"
        - "510"
        - "511"
      statusCodeValue:
        type: "integer"
        format: "int32"
  _SWRoute:
    type: "object"
    required:
    - "condition"
    - "destination"
    properties:
      createdBy:
        type: "string"
      createdDateTime:
        type: "string"
        format: "date-time"
      routeId:
        type: "string"
      updateDateTime:
        type: "string"
        format: "date-time"
      updatedBy:
        type: "string"
      version:
        type: "integer"
        format: "int64"
      condition:
        type: "string"
        example: "10001"
        description: "Condition Code"
      destination:
        type: "string"
        example: "FDD"
        description: "Destination Route Name"
  ContactInfo:
    type: "object"
    properties:
      email:
        type: "string"
      name:
        type: "string"
      role:
        type: "string"
  Route:
    type: "object"
    required:
    - "condition"
    - "destination"
    properties:
      condition:
        type: "string"
        example: "10001"
        description: "Condition Code"
      destination:
        type: "string"
        example: "FDD"
        description: "Destination Route Name"
  About:
    type: "object"
    properties:
      contacts:
        type: "array"
        items:
          $ref: "#/definitions/ContactInfo"
      docs:
        type: "string"
      summary:
        type: "string"
      versions:
        type: "array"
        items:
          type: "string"
  ErrorResponse:
    type: "object"
    properties:
      description:
        type: "string"
      details:
        type: "array"
        items:
          type: "object"
      errorCode:
        type: "string"
        enum:
        - "BAD_REQUEST"
        - "UNPROCESSABLE_ENTITY"
        - "INTERNAL_SERVER_ERROR"
        - "NOT_ACCEPTABLE"
        - "NOT_FOUND"
        - "CONFLICT"
      exception:
        type: "string"
      path:
        type: "string"
      status:
        type: "integer"
        format: "int32"
      timestamp:
        type: "string"
